name: Test

on:
    push:
        branches:
            - master
            - ci/*
    pull_request:
        branches: [ "master" ]

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Build
              run: cargo build --verbose
            - name: Run tests
              run: cargo test --verbose            